version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: alikhan
      POSTGRES_PASSWORD: alikhan123
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: nextjs_app
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://alikhan:alikhan123@postgres:5432/school
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      NEXT_PUBLIC_CLOUDINARY_API_KEY: ${NEXT_PUBLIC_CLOUDINARY_API_KEY}
    depends_on:
      - postgres

volumes:
  postgres_data:
